spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: davidis2b
    url: jdbc:mysql://localhost:3306/vidtube?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull


